version: '3'

services:
  server:
    build: ./
    depends_on:
      - 'database'
    command: sh -c 'npm install; npm run seed; npm start'
    ports: 
      - '3002:3002'

  database:
    image: mongo:latest
